# Generated by Django 4.1.7 on 2023-03-17 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PG_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cupboard', models.IntegerField(default=1)),
                ('no_of_beds', models.IntegerField(default=1)),
                ('pg_type', models.CharField(choices=[('AC', 'ac'), ('Non-AC', 'non-ac')], max_length=10)),
                ('pgdetails_id', models.CharField(max_length=50)),
                ('pg_image', models.ImageField(blank=True, null=True, upload_to='PG_images/')),
                ('desc', models.CharField(max_length=1000)),
                ('room_sharing', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=500)),
                ('near_by_place', models.CharField(max_length=200)),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PG_details',
            },
        ),
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('rooms', models.IntegerField(default=1)),
                ('room_sharing', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('pg_addres', models.CharField(max_length=500)),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PG',
            },
        ),
    ]
